
export const ADD_SITES_TRELLO_FAIL = 'ADD_SITES_TRELLO_FAIL';
export const ADD_SITES_TRELLO = 'ADD_SITES_TRELLO';
export const GET_SITES_TRELLO = 'GET_SITES_TRELLO';
export const GET_SITES_TRELLO_TRUE = 'GET_SITES_TRELLO_TRUE';
export const GET_SITES_TRELLO_FAIL = 'GET_SITES_TRELLO_FAIL';
export const ADD_SITE_UI = 'ADD_SITE_UI';
export const DELETE_NEWS = 'DELETE_NEWS';
export const DELETE_NEWS_UI = 'DELETE_NEWS_UI';


export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_TRUE = 'AUTH_LOGIN_TRUE';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const LOGIN_SUCCESS_TOKEN = 'LOGIN_SUCCESS_TOKEN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_REDIRECT_SIGNUP = 'AUTH_REDIRECT_SIGNUP';
export const AUTH_REDIRECT_SIGNIN = 'AUTH_REDIRECT_SIGNIN';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

